name: data_reliability_lab
version: 1.0.0
config-version: 2
profile: data_reliability_lab

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests", "models/marts/singular_tests"]
clean-targets: ["target", "dbt_packages"]

models:
  data_reliability_lab:
    staging:
      +materialized: view
    marts:
      +materialized: table
      singular_tests:
        +enabled: false

seeds:
  data_reliability_lab:
    +quote_columns: false
